package org.pac4j.jax.rs.rules;

import java.net.CookieHandler;
import java.net.CookieManager;
import java.util.Set;

import javax.ws.rs.ProcessingException;
import javax.ws.rs.client.Client;
import javax.ws.rs.client.WebTarget;
import javax.ws.rs.core.Application;

import org.assertj.core.util.Sets;
import org.awaitility.Awaitility;
import org.awaitility.Duration;
import org.glassfish.jersey.client.JerseyClientBuilder;
import org.jboss.resteasy.plugins.server.undertow.UndertowJaxrsServer;
import org.jboss.resteasy.test.TestPortProvider;
import org.junit.rules.ExternalResource;
import org.pac4j.jax.rs.features.JaxRsConfigProvider;
import org.pac4j.jax.rs.features.Pac4JSecurityFeature;
import org.pac4j.jax.rs.resteasy.features.Pac4JProfileInjectorFactory;
import org.pac4j.jax.rs.servlet.features.ServletJaxRsContextFactoryProvider;

import io.undertow.server.session.SessionCookieConfig;

public class RestEasyUndertowServletRule extends ExternalResource implements SessionContainerRule {

    private UndertowJaxrsServer server;

    private Client client;

    public class MyApp extends Application {

        @Override
        public Set<Class<?>> getClasses() {
            return getResources();
        }

        @Override
        public Set<Object> getSingletons() {
            return Sets.newLinkedHashSet(
                    new JaxRsConfigProvider(getConfig()),
                    new ServletJaxRsContextFactoryProvider(),
                    new Pac4JProfileInjectorFactory(),
                    new Pac4JSecurityFeature());
        }
    }

    @Override
    protected void before() throws Throwable {
        // Used by Jersey Client to store cookies
        CookieHandler.setDefault(new CookieManager());

        // we don't need a resteasy client, and the jersey one works better with redirect
        client = new JerseyClientBuilder().build();

        // TODO use an autogenerated port...
        System.setProperty("org.jboss.resteasy.port", "24257");
        server = new UndertowJaxrsServer().start();

        server.deploy(new MyApp());
    }

    @Override
    protected void after() {
        server.stop();
        // server.stop is not instantaneous
        Awaitility.await().atMost(Duration.FIVE_SECONDS).until(() -> {
            try {
                getTarget("/").request().get();
            } catch (ProcessingException e) {
                return true;
            }
            return false;
        });
        client.close();
        CookieHandler.setDefault(null);
    }

    @Override
    public WebTarget getTarget(String url) {
        return client.target(TestPortProvider.generateURL(url));
    }

    @Override
    public String cookieName() {
        return SessionCookieConfig.DEFAULT_SESSION_ID;
    }
}
